import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { css } from "@/styled-system/css";
import { DesktopNav } from "@/components/desktop-nav";
import { Suspense } from "react";
import { HomepageGraphic } from "./homepage-graphic";
import { MobileNav } from "@/components/mobile-nav";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={css({ height: "100%" })}>
      <body
        className={`${raleway.className} ${css({ backgroundColor: "gray", height: "100%" })}`}
      >
        <div
          className={css({
            display: "flex",
            flexDir: "column",
            height: "100dvh",
          })}
        >
          <main className={css({ flex: "1 1 auto", position: "relative" })}>
            <div
              className={css({
                position: "absolute",
                left: 0,
                top: 0,
                height: "300px",
                width: "300px",
                transform: "rotate(180deg)",
              })}
            >
              <Suspense>
                <HomepageGraphic />
              </Suspense>
            </div>

            {children}

            <div
              className={css({
                position: "absolute",
                right: 0,
                bottom: 0,
                height: "300px",
                width: "300px",
              })}
            >
              <Suspense>
                <HomepageGraphic />
              </Suspense>
            </div>
          </main>

          <div
            className={css({
              display: ["block", undefined, undefined, undefined, "none"],
              position: "absolute",
              top: 0,
              left: 0,
              height: "100%",
              width: "100%",
              pointerEvents: "none",
            })}
          >
            <MobileNav />
          </div>

          <div
            className={css({
              display: ["none", undefined, undefined, undefined, "block"],
              flex: "0 0 auto",
            })}
          >
            <DesktopNav />
          </div>
        </div>
      </body>
    </html>
  );
}
